name: perfect_contacts
description: "A Flutter plugin to manage device contacts easily. Fetch, add, update, and delete contacts with clean APIs. Works seamlessly across Android and iOS for apps that need efficient contact management."
version: 0.0.1
repository: https://github.com/DeveloperWaybee/flutter-perfect_contacts
issue_tracker: https://github.com/DeveloperWaybee/flutter-perfect_contacts/issues
homepage: https://waybeetech.com/

environment:
  sdk: ^3.9.2
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.waybeetech.perfect_contacts
        pluginClass: PerfectContactsPlugin
      ios:
        pluginClass: PerfectContactsPlugin

